### ISSUE TITLE
fatal error: 'uWS/uWS.h' file not found

### ISSUE THREAD

**Issue by OverRatedTech** [udacity/CarND-Path-Planning-Project#14]
I didn't touch any of main.cpp and I notice this error.

**Comment by dominikandreas** [comment]
You're missing the websockets library. Look inside the install_ubuntu.sh. it states:

```git clone https://github.com/uWebSockets/uWebSockets 
cd uWebSockets
# git checkout e94b6e1
mkdir build
cd build
cmake ..
make 
sudo make install```

Not sure why the checkout command is commented out, you may need that for compatibility with the code in main.cpp

**Comment by OverRatedTech** [comment]
Does it matter where we manage uWebSockets folder if we have both paths (/usr/local/include and /usr/include)?

**Comment by OverRatedTech** [comment]
I have a

**Comment by dominikandreas** [comment]
Generally it doesn't matter as long as the sources can be found by your toolchain.

**Comment by OverRatedTech** [comment]
toolchain? I googled an online setup and was wondering if this is the correct link to follow. 

https://esp-idf.readthedocs.io/en/v2.0/macos-setup.html

**Comment by dominikandreas** [comment]
Sorry, with toolchain I meant whatever set of tools you use for compiling. Your compiler needs to be able to find the sources you're linking. If you're using a mac, check out install-mac.sh and see if that works for you

**Comment by OverRatedTech** [comment]
Thank you! After Setting up  install-mac.sh on my terminal, everything compiles.

**Comment by OverRatedTech** [comment]
Also I notice I didn't have to call

git clone https://github.com/uWebSockets/uWebSockets 
cd uWebSockets
git checkout e94b6e1

Is this something I should worry about even though my code compiled?

**Comment by dominikandreas** [comment]
Those commands should have been automatically executed when you called
``install-mac.sh``

**Comment by deniskrop** [comment]
@rchavezj  Were you ever able to fix this issue? I'm running into it in XCode.

**Comment by rchavezj** [comment]
I'm sorry but I haven't touched the code in almost a year. I believe @dominikandreas was right tho because I remember the program worked eventually. Gluck @deniskrop

**Comment by bobo7727** [comment]
# Install uWebSockets
# See Detail:  https://github.com/udacity/CarND-Path-Planning-Project/blob/master/install-ubuntu.sh
sudo apt-get install libuv1-dev libssl-dev libz-dev
git clone https://github.com/uWebSockets/uWebSockets 
cd uWebSockets
git checkout e94b6e1   #Important,CMakeList.txt in this commit.
mkdir build
cd build
cmake ..
make
sudo make install
sudo ln -s /usr/lib64/libuWS.so /usr/lib/libuWS.so  #Important, link libuWS.so
sudo rm -r uWebSockets
