### ISSUE TITLE
Add C++ testing framework

### ISSUE THREAD

**Issue by mreichelt** [udacity/CarND-Path-Planning-Project#21]
In order for Udacity CarND students to be able to write unit-tests for their C++ code each of them would need to set up a C++ testing framework first by messing with the `CMakeList.txt` file. This can be tedious and error-prone.

By adding a C++ testing framework by default we can improve the development experience and make life of students easier.

**Comment by baumanab** [comment]
This is a good suggestion.  However, adding a testing framework is currently out of scope for this project.
