### ISSUE TITLE
path_planning executable terminates when I start the simulator

### ISSUE THREAD

**Issue by skbhat** [udacity/CarND-Path-Planning-Project#26]
Hello,

I start the executable by

> ./path_planning
Listening to port 4567

Then when I start the simulator and start the autonomous mode I get the following error

Connected!!!
terminate called after throwing an instance of 'std::domain_error'
  what():  type must be number, but is null
Aborted (core dumped)

I am using Ubuntu 16.04

thanks in advance
skbhat

**Comment by mvirgo** [comment]
Hi there - were you able to figure out this issue? It would appear to be from the code implemented outside of the provided code, but just wanted to check.

**Comment by skbhat** [comment]
Sorry, I forgot to update this thread.  It was occurring because I was using incorrect simulator.  This simulator belonging to another project was using the same port.
