### ISSUE TITLE
install-ubuntu.sh problem

### ISSUE THREAD

**Issue by subodh-malgonde** [udacity/CarND-Path-Planning-Project#3]
The 5th line of the file which checks out the uWebSockets repo to a particular commit, is commented:
```

git clone https://github.com/uWebSockets/uWebSockets 
cd uWebSockets
# git checkout e94b6e1
```
This causes problems during installation because the make command expects a `CMakeLists.txt` file, which does not exist if you do not perform `git checkout e94b6e1`.

**Comment by AloshkaD** [comment]
Awesome, thanks man, I was stuck on that and tried to compile the source directly but that didn't help. Now it works!

**Comment by baumanab** [comment]
Thanks for letting us know.  This has been corrected.
