### ISSUE TITLE
uWebSockets cmake error

### ISSUE THREAD

**Issue by engrmasood2002** [udacity/CarND-Path-Planning-Project#33]
Hi
When i run command cmake ..
I get error
CMake Error: The source directory "/home/masood" does not appear to contain CMakeLists.txt.
Any Solution

Thanks

**Comment by mvirgo** [comment]
Hi there! I have two questions to help debug:
1) Are you running `cmake .. && make` from within a `build` folder, that is outside of the `src` folder (i.e. in the main directory)?
2) If so, is `CMakeLists.txt` in the main directory, i.e. one level above the `build` and `src` folders?

**Comment by cseas** [comment]
I'm also getting a similar error.
Answer to both the questions above is Yes.

**Comment by mvirgo** [comment]
No further comments on the original issue, which appears to just be from running cmake from the incorrect directory, so I'll close this one out.
