### ISSUE TITLE
uWebSockets variables LIBUV_INCLUDE_DIR and LIBUV_LIBRARY NOTFOUND error

### ISSUE THREAD

**Issue by engrmasood2002** [udacity/CarND-Path-Planning-Project#34]
Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2g")  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/home/masood/uWebSockets/LIBUV_INCLUDE_DIR
   used as include directory in directory /home/masood/uWebSockets
LIBUV_LIBRARY
    linked by target "uWS" in directory /home/masood/uWebSockets

-- Configuring incomplete, errors occurred!

**Comment by ysonggit** [comment]
I had the same issue.

**Comment by mvirgo** [comment]
Closing this one out - libuv is included in the install scripts.
