### ISSUE TITLE
Nothing happened after Connected!!!.

### ISSUE THREAD

**Issue by jojo666666** [udacity/CarND-Path-Planning-Project#46]
Hello,
When  i run $ ./path_planning and start the term3_sim.x86_64,it shows that
Listening to port 4567
Connected!!!
But I can only use the manual mode.
Can you tell me how to start the autonomous mode?

thanks in advance
jojo666666

**Comment by mvirgo** [comment]
Hi there! There's actually not a separate autonomous mode on this one; if you are feeding in the values the simulator expects then the car will start moving.

You'll essentially want to feed two arrays into the json message given new x,y coordinates:
```
msgJson["next_x"] = next_x_vals;
msgJson["next_y"] = next_y_vals;
```

So most of the magic should happen prior to this, and generate the coordinates you place into (in this example) `next_x_vals` and `next_y_vals`.

**Comment by jojo666666** [comment]
Thanks for your timely reply.

I just understand the purpose of your project. This virtual simulation environment is of great significance to our students.
If anyone else wants to just try as I did, you can refer to the supplement @jeremy-shannon.
https://github.com/jeremy-shannon/CarND-Path-Planning-Project

Now I'm going to close this issue. 
Thank you again.
