### ISSUE TITLE
Add units to car variables

### ISSUE THREAD

**Issue by githubrandomuser2017** [udacity/CarND-Path-Planning-Project#57]
The `README.md` file says:

```
Main car's localization Data (No Noise)

["x"] The car's x position in map coordinates

["y"] The car's y position in map coordinates

["s"] The car's s position in frenet coordinates

["d"] The car's d position in frenet coordinates

["yaw"] The car's yaw angle in the map

["speed"] The car's speed in MPH
```

Please add units to the variables. Are the x, y, s, and d in meters? Is the yaw in degrees or radians?

**Comment by UAnjali** [comment]
Hi @githubrandomuser2017,
The variables x, y, s, and d are coordinates here, that is why no units are given. We suggest you refer to the Knowledge hub and reach out to your assigned mentor for user-specific issues. 
Thanks
