### ISSUE TITLE
Unity Simulator Term 3 Sources

### ISSUE THREAD

**Issue by dominikandreas** [udacity/CarND-Path-Planning-Project#9]
For some reason I can't find the sources for the term 3 release of the self driving car simulator. All the contents in the repository relate to the previous term (jungle and lake tracks), but not to what I can see in the release version. Is anyone able to provide the sources for this?

**Comment by happyguard91** [comment]
Yeah, I am also having trouble finding one...

**Comment by mvirgo** [comment]
Make sure you are on the [Term 3 branch](https://github.com/udacity/self-driving-car-sim/tree/term3_collection). If you have continued issues with the open source simulator files, please leave them within the simulator repository itself.
